Salesforce Account

CREATE TABLE `SF_ACCOUNT` (
  `_timestamp` mediumtext,
  `AccountSource` varchar(45) DEFAULT NULL,
  `Account_Classification__c` varchar(45) DEFAULT NULL,
  `Activation_Date_Populated__c` varchar(45) DEFAULT NULL,
  `Activation_Date__c` varchar(45) DEFAULT NULL,
  `Active_Customer__c` varchar(45) DEFAULT NULL,
  `Active_User__c` varchar(45) DEFAULT NULL,
  `BillingCity` varchar(45) DEFAULT NULL,
  `BillingCountry` varchar(45) DEFAULT NULL,
  `BillingPostalCode` varchar(45) DEFAULT NULL,
  `BillingState` varchar(45) DEFAULT NULL,
  `BillingStreet` varchar(999) DEFAULT NULL,
  `Channel__c` varchar(45) DEFAULT NULL,
  `Closed_Date_Roll_up__c` varchar(45) DEFAULT NULL,
  `Closed_Won_Opportunity_Value_New__c` varchar(45) DEFAULT NULL,
  `Competitor__c` varchar(45) DEFAULT NULL,
  `CreatedDate` varchar(45) DEFAULT NULL,
  `CurrencyIsoCode` varchar(45) DEFAULT NULL,
  `Customer_Activation_Date__c` varchar(45) DEFAULT NULL,
  `Customer_count__c` varchar(45) DEFAULT NULL,
  `Date_Attended_a_BootCamp_Campaign__c` varchar(45) DEFAULT NULL,
  `Days_since_Last_Activity__c` varchar(45) DEFAULT NULL,
  `Deactivation_Date_12__c` varchar(45) DEFAULT NULL,
  `Deactivation_Date__c` varchar(45) DEFAULT NULL,
  `Field_Sales_Owner__c` varchar(45) DEFAULT NULL,
  `Financial_Year_End_Date__c` varchar(45) DEFAULT NULL,
  `Id` varchar(45) DEFAULT NULL,
  `Includes_Consulting__c` varchar(45) DEFAULT NULL,
  `Includes_Dev_Support__c` varchar(45) DEFAULT NULL,
  `Includes_QuickStart__c` varchar(45) DEFAULT NULL,
  `IsDeleted` varchar(45) DEFAULT NULL,
  `LastActivityDate` varchar(45) DEFAULT NULL,
  `Last_Activity_Date__c` varchar(45) DEFAULT NULL,
  `Lost_Customer__c` varchar(45) DEFAULT NULL,
  `Lost_Date_Override__c` varchar(45) DEFAULT NULL,
  `Lost_Date__c` varchar(45) DEFAULT NULL,
  `Lost_Reason__c` varchar(999) DEFAULT NULL,
  `MasterRecordId` varchar(45) DEFAULT NULL,
  `Most_Recent_Opp_Amount__c` varchar(45) DEFAULT NULL,
  `Most_Recent_Opp_Name__c` varchar(999) DEFAULT NULL,
  `Name` varchar(999) DEFAULT NULL,
  `OwnerId` varchar(45) DEFAULT NULL,
  `ParentId` varchar(45) DEFAULT NULL,
  `Partner_Driven__c` varchar(45) DEFAULT NULL,
  `Partner_Level__c` varchar(45) DEFAULT NULL,
  `Partner_Logo__c` varchar(999) DEFAULT NULL,
  `Partner_Start_Date__c` varchar(45) DEFAULT NULL,
  `Phone` varchar(45) DEFAULT NULL,
  `Rating` varchar(45) DEFAULT NULL,
  `Recent_Bootcamp_Attendance_Date__c` varchar(45) DEFAULT NULL,
  `RecordTypeId` varchar(45) DEFAULT NULL,
  `Region__c` varchar(45) DEFAULT NULL,
  `Salesforce_record_id__c` varchar(45) DEFAULT NULL,
  `ShippingCity` varchar(45) DEFAULT NULL,
  `ShippingCountry` varchar(45) DEFAULT NULL,
  `ShippingPostalCode` varchar(45) DEFAULT NULL,
  `ShippingState` varchar(45) DEFAULT NULL,
  `ShippingStreet` varchar(999) DEFAULT NULL,
  `SicDesc` varchar(45) DEFAULT NULL,
  `Subscription_Activation_Date__c` varchar(45) DEFAULT NULL,
  `Subscription_Booking_Date__c` varchar(45) DEFAULT NULL,
  `Subscription_Deactivation_Date__c` varchar(45) DEFAULT NULL,
  `Sub_Catergory__c` varchar(45) DEFAULT NULL,
  `Technical_Owner__c` varchar(45) DEFAULT NULL,
  `Type` varchar(45) DEFAULT NULL,
  `Type_Code_Rollup__c` varchar(45) DEFAULT NULL,
  `Unique_Key__c` varchar(45) DEFAULT NULL,
  `User_ID__c` varchar(45) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


Salesforce opportunities


CREATE TABLE `SF_OPPORTUNITY` (
  `_timestamp` bigint(20) DEFAULT NULL,
  `AccountId` varchar(45) DEFAULT NULL,
  `Action__c` varchar(999) DEFAULT NULL,
  `Amount` varchar(45) DEFAULT NULL,
  `Best_Case_Amount__c` varchar(45) DEFAULT NULL,
  `Breakdown_Type__c` varchar(45) DEFAULT NULL,
  `Channel_error__c` varchar(45) DEFAULT NULL,
  `CloseDate` varchar(45) DEFAULT NULL,
  `Closed_Month__c` varchar(45) DEFAULT NULL,
  `Commission_included__c` varchar(45) DEFAULT NULL,
  `Competitor_we_Lost_to__c` varchar(45) DEFAULT NULL,
  `Confidence__c` varchar(45) DEFAULT NULL,
  `Contact_Roles__c` varchar(45) DEFAULT NULL,
  `Conversion_Date__c` varchar(45) DEFAULT NULL,
  `CreatedDate` varchar(45) DEFAULT NULL,
  `Created_Today__c` varchar(45) DEFAULT NULL,
  `CurrencyIsoCode` varchar(45) DEFAULT NULL,
  `Current_Year_Amount__c` varchar(45) DEFAULT NULL,
  `End_Date__c` varchar(45) DEFAULT NULL,
  `Engagement_Code__c` varchar(999) DEFAULT NULL,
  `Expected_Case_Amount__c` varchar(45) DEFAULT NULL,
  `First_Account_Sale__c` varchar(45) DEFAULT NULL,
  `Fiscal` varchar(45) DEFAULT NULL,
  `FiscalQuarter` varchar(45) DEFAULT NULL,
  `FiscalYear` varchar(45) DEFAULT NULL,
  `Id` varchar(45) DEFAULT NULL,
  `If_Lost_Reason_Other_Please_Explain__c` varchar(999) DEFAULT NULL,
  `Implied_Exchange_Rate__c` varchar(45) DEFAULT NULL,
  `Includes_Consulting__c` varchar(45) DEFAULT NULL,
  `Includes_Dev_Support__c` varchar(45) DEFAULT NULL,
  `Includes_Production_Support__c` varchar(45) DEFAULT NULL,
  `Includes_QuickStart__c` varchar(45) DEFAULT NULL,
  `IsClosed` varchar(45) DEFAULT NULL,
  `IsDeleted` varchar(45) DEFAULT NULL,
  `IsWon` varchar(45) DEFAULT NULL,
  `LastActivityDate` varchar(45) DEFAULT NULL,
  `LastModifiedDate` varchar(45) DEFAULT NULL,
  `Last_Account_Sale__c` varchar(45) DEFAULT NULL,
  `LeadSource` varchar(45) DEFAULT NULL,
  `Lead_Type__c` varchar(45) DEFAULT NULL,
  `Line_Item_Divergence__c` varchar(45) DEFAULT NULL,
  `Line_Item_Total_Amount_USD__c` varchar(45) DEFAULT NULL,
  `Name` varchar(999) DEFAULT NULL,
  `New_Breakdown_Type__c` varchar(45) DEFAULT NULL,
  `Opportunity_Term__c` varchar(45) DEFAULT NULL,
  `Opp_End_Date__c` varchar(45) DEFAULT NULL,
  `Opp_Start_Date__c` varchar(45) DEFAULT NULL,
  `OwnerId` varchar(45) DEFAULT NULL,
  `Partnership__c` varchar(45) DEFAULT NULL,
  `Partner_commission__c` varchar(45) DEFAULT NULL,
  `Partner_Lead_Amount__c` varchar(45) DEFAULT NULL,
  `Partner_Lead_Close_Date__c` varchar(45) DEFAULT NULL,
  `Partner_Registration_Expires__c` varchar(45) DEFAULT NULL,
  `Partner_Registration_Status__c` varchar(45) DEFAULT NULL,
  `Partner_Sales_Contact_Email__c` varchar(45) DEFAULT NULL,
  `Partner_Sales_Contact_Name__c` varchar(45) DEFAULT NULL,
  `Prev_Year_Amount__c` varchar(45) DEFAULT NULL,
  `Pricebook2Id` varchar(45) DEFAULT NULL,
  `Prior_Stage__c` varchar(45) DEFAULT NULL,
  `Production_Support_Amount__c` varchar(45) DEFAULT NULL,
  `Products_in_use__c` varchar(999) DEFAULT NULL,
  `Project_Code__c` varchar(45) DEFAULT NULL,
  `Project__c` varchar(999) DEFAULT NULL,
  `Reason_Lost__c` varchar(45) DEFAULT NULL,
  `RecordTypeId` varchar(45) DEFAULT NULL,
  `Referred_to_Partners__c` varchar(45) DEFAULT NULL,
  `Registered_by__c` varchar(45) DEFAULT NULL,
  `Renewal_Stage__c` varchar(45) DEFAULT NULL,
  `RFI_RFQ_RFP_BID__c` varchar(45) DEFAULT NULL,
  `Salesforce_Record_Id__c` varchar(45) DEFAULT NULL,
  `Services_Amount__c` varchar(45) DEFAULT NULL,
  `SFDC__c` varchar(45) DEFAULT NULL,
  `StageName` varchar(45) DEFAULT NULL,
  `Stage_Change_Date__c` varchar(45) DEFAULT NULL,
  `Start_Date__c` varchar(45) DEFAULT NULL,
  `Subscription_Activation_Date_del__c` varchar(45) DEFAULT NULL,
  `Subscription_Deactivation_Date__c` varchar(45) DEFAULT NULL,
  `Test_Formula__c` varchar(45) DEFAULT NULL,
  `Type` varchar(45) DEFAULT NULL,
  `Type_Code__c` varchar(45) DEFAULT NULL,
  `unique_count__c` varchar(45) DEFAULT NULL,
  `Worse_Case_Amount__c` varchar(45) DEFAULT NULL,
  `Zero_Amount__c` varchar(45) DEFAULT NULL,
  `ThisMonth` int(11) DEFAULT NULL,
  `ThisQuarter` int(11) DEFAULT NULL,
  `ThisYear` int(11) DEFAULT NULL,
  `NextMonth` int(11) DEFAULT NULL,
  `NextQuarter` int(11) DEFAULT NULL,
  `NextYear` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Salesforce Lead


CREATE TABLE `SF_LEAD` (
  `_timestamp` mediumtext,
  `Account_Category__c` varchar(255) DEFAULT NULL,
  `Account_Profile_Score__c` varchar(255) DEFAULT NULL,
  `Amount_Paid__c` varchar(255) DEFAULT NULL,
  `Amount__c` varchar(255) DEFAULT NULL,
  `Campaign_Source__c` varchar(255) DEFAULT NULL,
  `City` varchar(100) DEFAULT NULL,
  `Cloud_Type__c` varchar(100) DEFAULT NULL,
  `Company` varchar(100) DEFAULT NULL,
  `Competitors__c` varchar(100) DEFAULT NULL,
  `ConvertedAccountId` varchar(100) DEFAULT NULL,
  `ConvertedContactId` varchar(100) DEFAULT NULL,
  `ConvertedDate` varchar(100) DEFAULT NULL,
  `ConvertedOpportunityId` varchar(100) DEFAULT NULL,
  `Country` varchar(100) DEFAULT NULL,
  `CreatedDate` varchar(100) DEFAULT NULL,
  `CurrencyIsoCode` varchar(100) DEFAULT NULL,
  `Detailed_Status__c` varchar(255) DEFAULT NULL,
  `Disqualified_Reason__c` varchar(100) DEFAULT NULL,
  `DoNotCall` varchar(100) DEFAULT NULL,
  `Email` varchar(100) DEFAULT NULL,
  `FirstName` varchar(100) DEFAULT NULL,
  `First_Contact_Date__c` varchar(100) DEFAULT NULL,
  `HasOptedOutOfEmail` varchar(100) DEFAULT NULL,
  `HasOptedOutOfFax` varchar(100) DEFAULT NULL,
  `Hot__c` varchar(100) DEFAULT NULL,
  `How_lead_found_about_WSO2__c` varchar(100) DEFAULT NULL,
  `Id` varchar(100) DEFAULT NULL,
  `IsConverted` varchar(100) DEFAULT NULL,
  `IsDeleted` varchar(100) DEFAULT NULL,
  `IsUnreadByOwner` varchar(100) DEFAULT NULL,
  `Job_Role__c` varchar(100) DEFAULT NULL,
  `LastActivityDate` varchar(100) DEFAULT NULL,
  `Last_Activity_Date__c` varchar(100) DEFAULT NULL,
  `LeadSource` varchar(100) DEFAULT NULL,
  `Lead_Activity_Score__c` varchar(100) DEFAULT NULL,
  `Lead_Business_Profile_Score__c` varchar(100) DEFAULT NULL,
  `Lead_Channel__c` varchar(100) DEFAULT NULL,
  `Lead_Profile_Score__c` varchar(100) DEFAULT NULL,
  `Lead_Source_Details__c` varchar(100) DEFAULT NULL,
  `Lead_Source_detail__c` varchar(100) DEFAULT NULL,
  `Lead_Type__c` varchar(100) DEFAULT NULL,
  `MobilePhone` varchar(100) DEFAULT NULL,
  `Most_Recent_CTA__c` varchar(100) DEFAULT NULL,
  `Most_Recent_Lead_Source__c` varchar(100) DEFAULT NULL,
  `Name` varchar(100) DEFAULT NULL,
  `No_of_Participants__c` varchar(100) DEFAULT NULL,
  `NumberOfEmployees` varchar(100) DEFAULT NULL,
  `Opportunity_Amount__c` varchar(100) DEFAULT NULL,
  `Opportunity_Close_Date__c` varchar(100) DEFAULT NULL,
  `Opportunity_in_Play__c` varchar(100) DEFAULT NULL,
  `OwnerId` varchar(100) DEFAULT NULL,
  `Partner_Registration_Expires__c` varchar(100) DEFAULT NULL,
  `Partner_Registration_Status__c` varchar(100) DEFAULT NULL,
  `Partner_Sales_Contact_Email__c` varchar(100) DEFAULT NULL,
  `Partner_Sales_Contact_Name__c` varchar(100) DEFAULT NULL,
  `Partner_SQL_Date__c` varchar(100) DEFAULT NULL,
  `Payment_Status__c` varchar(100) DEFAULT NULL,
  `Payment_Type__c` varchar(100) DEFAULT NULL,
  `Phone` varchar(100) DEFAULT NULL,
  `PostalCode` varchar(100) DEFAULT NULL,
  `Product_Of_Interest__c` varchar(999) DEFAULT NULL,
  `Rating` varchar(100) DEFAULT NULL,
  `Region__c` varchar(100) DEFAULT NULL,
  `Registered_by__c` varchar(100) DEFAULT NULL,
  `Rw_Source__c` varchar(100) DEFAULT NULL,
  `Salesforce_Record_Id__c` varchar(100) DEFAULT NULL,
  `Salutation` varchar(100) DEFAULT NULL,
  `SFDC_Existing_Account__c` varchar(100) DEFAULT NULL,
  `SFDC_Existing_Contact__c` varchar(100) DEFAULT NULL,
  `SQL_Date__c` varchar(100) DEFAULT NULL,
  `SQL__c` varchar(100) DEFAULT NULL,
  `State` varchar(100) DEFAULT NULL,
  `Status` varchar(100) DEFAULT NULL,
  `Street` varchar(999) DEFAULT NULL,
  `SystemModstamp` varchar(100) DEFAULT NULL,
  `Title` varchar(100) DEFAULT NULL,
  `Total_Fee__c` varchar(100) DEFAULT NULL,
  `Type_of_service__c` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;






+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


Jenkins buildData


CREATE TABLE `JNKS_BUILDDATA` (
  `Timestamp` timestamp NULL DEFAULT NULL,
  `Product` varchar(100) DEFAULT '',
  `Component` varchar(100) DEFAULT '',
  `BuildStatus` varchar(30) DEFAULT NULL,
  `BuildNumber` int(11) DEFAULT NULL,
  KEY `fk_comp` (`Product`,`Component`),
  CONSTRAINT `fk_comp` FOREIGN KEY (`Product`, `Component`) REFERENCES `JNKS_COMPONENTPRODUCT` (`Product`, `Component`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;




++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


Jenkins component


CREATE TABLE `JNKS_COMPONENTPRODUCT` (
  `Product` varchar(100) NOT NULL,
  `Component` varchar(100) NOT NULL,
  PRIMARY KEY (`Product`,`Component`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;




